// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "1e1118b93744ce999a51837c3e1cda32a2e920c9bff62916ed123656a83d4849")
